---
- name: Generate RSA key
  command: openssl genrsa -out {{ rabbitmq_conf_ssl_options_keyfile }} 2048 creates={{ rabbitmq_conf_ssl_options_keyfile }}

- name: Generate CSR
  command: openssl req -new -subj "{{ ssl_certs_fields }}" -key {{ rabbitmq_conf_ssl_options_keyfile }} -out /tmp/rabbitmq_cert.csr creates=/tmp/rabbitmq_cert.csr

- name: Generate self-signed SSL certificate
  command: openssl req -nodes -x509 -days {{ ssl_certs_days }} -in /tmp/rabbitmq_cert.csr -key {{ rabbitmq_conf_ssl_options_keyfile }} -out {{ rabbitmq_conf_ssl_options_certfile }} -extensions v3_ca creates={{ rabbitmq_conf_ssl_options_certfile }}
